### ISSUE TITLE
old.reddit.com

### ISSUE THREAD

**Issue by celsoazevedo** [nickrussler/Reddit-Link-Opener#14]
Now that www.reddit.com uses a new design, it would be nice if Reddit Link Opener supported the "old.reddit.com" URL.

They plan to keep the old design working on this subdomain: https://www.reddit.com/r/beta/comments/8lv96l/feedback_please_dont_ever_remove_oldredditcom/dziwf1p/

**Comment by nickrussler** [comment]
Just published a simple patch for new layout.

**Comment by nickrussler** [comment]
I now also added support for the old layout and old.reddit.com

**Comment by celsoazevedo** [comment]
I can confirm that `1.7.1` works on `www.reddit.com` with the new and old layout and on `old.reddit.com`.

Thanks!
