### ISSUE TITLE
Keyboard Shortcut: Validation of the Setting

### ISSUE THREAD

**Issue by JaHolliman** [nickrussler/Reddit-Link-Opener#3]
There is no validation when the keyboard shortcut setting has been assigned a value.

A simple way to fix this problem and another [issue](https://github.com/nickrussler/F7U12-Link-Opener/issues/2A) would be to create a simple form with checkboxes for the key modifiers (**e.g.** "_Cntl_"), and a text box for assigning which key activates the shortcut (**e.g.** "_T_").

**Comment by nickrussler** [comment]
Hi, this sounds like a good solution. I would be happy to merge a pull request!
