### ISSUE TITLE
Comments Only?

### ISSUE THREAD

**Issue by xnamkcor** [nickrussler/Reddit-Link-Opener#4]
Can you make an option to only open the comments for all the posts?

**Comment by edcaron** [comment]
I'd like to have this option. Was about to open a request but i see that there are more people interested. It would be nice if it was possible.

**Comment by nickrussler** [comment]
If I find some time, I will consider implementing it.

**Comment by edcaron** [comment]
I did it and made a pull request. If you have time, take a look and tell me what you find. I can change for you.
