### ISSUE TITLE
Doesn't mark links visited on another computer with Gold

### ISSUE THREAD

**Issue by Loosenutt** [nickrussler/Reddit-Link-Opener#5]
Firstly, love the extension!!

I have Reddit Gold, mainly to keep track of which links I have clicked on between PCs.

When I use Link Opener on PC1 it works exactly as expected. However when I go to PC2 all the links opened by Link Opener on PC1 is still blue on PC2. 

If I click on the links manually on PC1, then they appear purple (visited) on PC2, so the Reddit Gold feature is working fine.

I would be happy to donate $50 to your favorite charity, beer fund, etc. if you can add this feature / fix this bug.

Cheers

**Comment by nickrussler** [comment]
Hi, i fixed the bug and published the new version to the Chrome Web Store.
I would be really happy if you would donate to Doctors Without Borders, thank you very much!

**Comment by Loosenutt** [comment]
Hi,

Thank you very much for the quick turnaround.

Please find attached the donation receipt in the name of Reddit Link Opener

Cheers
