### ISSUE TITLE
Extension broken with latest chromium?

### ISSUE THREAD

**Issue by tueksta** [nickrussler/Reddit-Link-Opener#6]
I updated my browser to `User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.64 Safari/537.36 Vivaldi/1.6.682.3` and all of a sudden reddit links aren't opening in a new tab anymore. The extension is still installed, updated to latest version and active. Any idea?

**Comment by nickrussler** [comment]
Can't reproduce with Chrome version 57.0.2939.0 canary (64-bit) under Windows. Maybe interference with another extension?

**Comment by tueksta** [comment]
Works again, not sure what it was, thanks
