### ISSUE TITLE
Feature Request: Exit Button

### ISSUE THREAD

**Issue by hamckio** [nickrussler/Reddit-Link-Opener#7]
I have been procrastinating a lot since I installed this extension.
Maybe could add a feature with a big red "EXIT" button that will close all reddit tabs in case of emergency where you need to go back to your life and do meaningful things.

**Comment by nickrussler** [comment]
Hi, sounds great! But where in the UI would you like to add the Button?

**Comment by nickrussler** [comment]
Since I think this task should be left for another extension, I am going to close this Issue :)

**Comment by hamckio** [comment]
Yeah my bad, I was high and half-serious when I raised that issue.
