### ISSUE TITLE
Some links not being marked as visited

### ISSUE THREAD

**Issue by mrlucas** [nickrussler/Reddit-Link-Opener#8]
First of all, I've been using this extension for years, and I love it. With that being said, this started a couple months ago; it only marks some of the links as being visited. 
Steps to reproduce:
Load up reddit in tab 1, control+shift+F 
close all new tabs, return to reddit in tab 1.
control+shift+F 
Many of the same posts get re-opened.
Only some of the links that were opened were marked as visited, others remain blue.  If you hover over one of the blue links that was visited it turns purple.  If you refresh reddit, the links are purple as expected, but this is not a good option as I use RES and never-ending-reddit which appends concurrent pages of reddit to the DOM once you're at the bottom of the page, and refreshing brings you back to page 1.

**Comment by nickrussler** [comment]
Hi, thanks for reporting this issue! Can you reproduce it with a fresh installation of chrome? Without any other extensions?

**Comment by mrlucas** [comment]
I have some more information, and a better way to test.  Change the number
of links you open to 1.  Open up an obscure subreddit that doesn't have any
visited links in it and fire the shortcut.  Several of the links will take
2 firings for it to register as being visited, so they will open twice.  I
tried a windows 7 VM that has a fresh install of chrome in it and no
extensions, and it has the same behavior. I also logged in into a remote
server and it does the same thing there, so it's not specific to my network
either.

**Comment by nickrussler** [comment]
I'm pretty sure the bug is related to Chrome storing a different URL in the history than the one that is in the link on Reddit (see [here](https://github.com/nickrussler/Reddit-Link-Opener/blob/master/src/backgroundpageScript.js#L58)). I think I can fix this by adding the `visited` class to the title element. I will try that ASAP.

**Comment by nickrussler** [comment]
I now add the `visited` class manually to parent element. This seemed to do the trick for me. I rolled out the new version, please tell if it worked for you.

**Comment by mrlucas** [comment]
Some of the links still remain blue on the reddit page, but they aren't
re-opened, so that's good enough for me!  Thanks!

**Comment by nickrussler** [comment]
Nice!
