### ISSUE TITLE
Option to open reddituploads.com images as images?

### ISSUE THREAD

**Issue by mf1776** [nickrussler/Reddit-Link-Opener#9]
With the new reddit image host, a thread now opens with a preview of the image with the comment section. Would it be possible to add an option so that the image is directly opened instead without the comments?

**Comment by nickrussler** [comment]
Yes, the image url can be found in the `data-url` of the corresponding `thing` element. When I find some time I will build this into the "Open Links directly" option.

**Comment by nickrussler** [comment]
Done, I uploaded the new version. Please tell me if you should experience bugs.

**Comment by mf1776** [comment]
works great thank you
